### ISSUE TITLE
Need Blog Post Preview Pictures

### ISSUE THREAD

**Issue by uaarg** [uaarg/uaarg.github.io#2]
**Description:**
Pictures would make posts more appealing to visitors. We don't have a system set up for it though

**Tasks:**
- [ ] Develop some way to add pictures to blog posts. 
- [ ] Needs to be backwards compatible to having *no pictures*.
- [ ] Optional: Some way to retrieve pictures already in blog posts and add them to preview? Not sure if possible with liquid. May need to edit posts directly with scripts
