### ISSUE TITLE
Misc Content Revision and Addition

### ISSUE THREAD

**Issue by uaarg** [uaarg/uaarg.github.io#3]
**Description:**
Miscellaneous Recommendations from other execs

**Tasks:**
- [ ] Check mailing link and email
- Description of Competitions and Community Workshops:
    - [ ] AUVSI - https://www.auvsi.org/
    - [ ] Highschool Drone workshop - See Kabir, Isha, Brian, Kayvon
- [ ] Sponsor page needs updating - See Kabir, Isha, Brian, Kayvon
