### ISSUE TITLE
Code Clean Up

### ISSUE THREAD

**Issue by rsandz** [uaarg/uaarg.github.io#5]
**Descriptions:**
We use the Incorporated theme for Jekyll. However, several changes have been made and we've heavily customized it. As such, several features are simply clutter at this point and should be removed.

**Tasks:**
- [ ] Remove references to "product" in config and pages.
- [ ] Clean up and document config.yml
- [ ] Clean up base and page templates
